from __future__ import annotations

import csv
from io import StringIO

import pytest

from retrieval_fairness.blast_radius import (
    build_blast_radius,
    render_blast_radius_csv,
    render_blast_radius_markdown,
    save_blast_radius,
)
from retrieval_fairness.diff import DiffReport
from retrieval_fairness.probe import ProbeResult


def _fixture():
    baseline = ProbeResult(
        freqs={
            "lost-low": 1,
            "lost-high": 4,
            "steady": 2,
            "rescued-low": 0,
            "rescued-high": 0,
        }
    )
    candidate = ProbeResult(
        freqs={
            "lost-low": 0,
            "lost-high": 0,
            "steady": 2,
            "rescued-low": 1,
            "rescued-high": 5,
        }
    )
    diff = DiffReport(
        coverage_delta=-0.1,
        gini_delta=0.2,
        hub_capture_top5_delta=0.0,
        dark_matter_delta=0.1,
        mean_query_overlap=0.125,
        workload_policy="same-content",
        corpus_policy="same-content",
    )
    return diff, baseline, candidate


def test_blast_radius_builds_deterministic_actionable_rows_from_raw_frequencies():
    diff, baseline, candidate = _fixture()
    report = build_blast_radius(
        diff,
        baseline,
        candidate,
        chunk_texts={
            "lost-high": "unsafe | <tag>\nnext",
            "rescued-high": 'comma, "quote"\nnext',
        },
    )

    assert [entry.chunk_id for entry in report.new_dark_matter] == ["lost-high", "lost-low"]
    assert [entry.chunk_id for entry in report.rescued] == ["rescued-high", "rescued-low"]
    assert report.new_dark_matter[0].baseline_frequency == 4
    assert report.new_dark_matter[0].candidate_frequency == 0
    assert report.new_dark_matter[0].delta == -4
    assert report.rescued[0].delta == 5
    assert report.to_dict()["summary"]["new_dark_matter_count"] == 2


def test_markdown_is_github_friendly_and_escapes_untrusted_chunk_text():
    diff, baseline, candidate = _fixture()
    report = build_blast_radius(
        diff,
        baseline,
        candidate,
        chunk_texts={"lost-high": "unsafe | <tag>\nnext"},
    )

    markdown = render_blast_radius_markdown(
        report,
        baseline_label="before.json",
        candidate_label="after.json",
    )

    assert markdown.startswith("# Migration blast radius\n")
    assert "| Newly dark-matter chunks | 2 |" in markdown
    assert "| Rescued chunks | 2 |" in markdown
    assert "unsafe \\| &lt;tag&gt;<br>next" in markdown
    assert markdown.index("lost-high") < markdown.index("lost-low")
    assert markdown.endswith("_Generated by `retrieval-fairness diff`._\n")


def test_markdown_omits_empty_text_column_without_explicit_corpus_enrichment():
    diff, baseline, candidate = _fixture()
    report = build_blast_radius(diff, baseline, candidate)

    markdown = render_blast_radius_markdown(report)

    assert "| Text |" not in markdown
    assert "lost-high" in markdown


def test_markdown_bounds_text_for_pr_review_and_allows_lossless_opt_in():
    diff, baseline, candidate = _fixture()
    long_text = "x" * 300
    report = build_blast_radius(diff, baseline, candidate, chunk_texts={"lost-high": long_text})

    bounded = render_blast_radius_markdown(report, max_text_chars=20)
    lossless = render_blast_radius_markdown(report, max_text_chars=0)

    assert "xxxxxxxxxxxxxxxxxxx…" in bounded
    assert "truncated to 20 characters" in bounded
    assert long_text not in bounded
    assert long_text in lossless
    assert "truncated to" not in lossless
    with pytest.raises(ValueError, match="non-negative"):
        render_blast_radius_markdown(report, max_text_chars=-1)


def test_csv_has_stable_schema_and_preserves_multiline_text():
    diff, baseline, candidate = _fixture()
    expected_text = 'comma, "quote"\nnext'
    report = build_blast_radius(
        diff,
        baseline,
        candidate,
        chunk_texts={"rescued-high": expected_text},
    )

    rows = list(csv.DictReader(StringIO(render_blast_radius_csv(report))))

    assert [row["change"] for row in rows] == [
        "new_dark_matter",
        "new_dark_matter",
        "rescued",
        "rescued",
    ]
    assert rows[2]["chunk_id"] == "rescued-high"
    assert rows[2]["candidate_frequency"] == "5"
    assert rows[2]["delta"] == "5"
    assert rows[2]["text"] == expected_text


def test_save_blast_radius_creates_parent_and_validates_format(tmp_path):
    diff, baseline, candidate = _fixture()
    report = build_blast_radius(diff, baseline, candidate)
    target = tmp_path / "artifacts" / "blast.md"

    save_blast_radius(report, target)

    assert target.read_text(encoding="utf-8").startswith("# Migration blast radius")
    with pytest.raises(ValueError, match="output_format"):
        save_blast_radius(report, tmp_path / "bad.out", output_format="json")


def test_blast_radius_rejects_non_text_enrichment():
    diff, baseline, candidate = _fixture()
    with pytest.raises(ValueError, match="must be text"):
        build_blast_radius(diff, baseline, candidate, chunk_texts={"lost-high": 123})  # type: ignore[dict-item]
